---
- name: Install nginx
  hosts: servers
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
    - name: Start nginx
      service:
        name: nginx
        state: started
    - name: Update index page
      copy:
        src: ../src/index.html
        dest: /var/www/html/index.html