name: Master deployment

on:
  push:
    branches:
      - master

jobs:
  Deploy-on-Master:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install ansible 
        run: sudo apt install -y ansible
      - name: Run playbook
        uses: andreabiondo/action-ansible-playbook@v2
        with:
          playbook: ansible-master.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          directory: ansible
          inventory: |
            [servers]
            production ansible_ssh_host=172.16.226.158
